---
title: "Reproducible Research: Peer Assessment 1"
author: "Fraukje Coopmans"
output: 
  html_document:
    keep_md: true
---

Loading and pre-processing the data
```{r}
#Read the csv file
activity_data <- read.csv("activity.csv")

#Ignore rows with NA values
activity_data_clean <- na.omit(activity_data); rm(activity_data)
```

What is mean total number of steps taken per day?
```{r}
#First, calculate the total number of steps taken on a date (day)
totalsteps_perday <- aggregate(activity_data_clean$steps, list(activity_data_clean$date), FUN=sum)$x

#Then, plot the histogram of total steps taken per day
h <- hist(totalsteps_perday, plot = FALSE)
plot(h, 
     xlab = 'Total number of steps taken per day', 
     main = 'Histogram: Steps per day', 
     col = 'green')

#Finally, print the mean and median
cat('Mean of the total number of steps taken per day: ', mean(totalsteps_perday, na.rm = TRUE)); cat('\n')
cat('Median of the total number of steps taken per day: ', median(totalsteps_perday, na.rm = TRUE))
```

What is the average daily activity pattern?
```{r}
#Find the average number of steps per interval
averagesteps_perinterval <- aggregate(activity_data_clean$steps, list(activity_data_clean$interval), FUN=mean)

#Plot interval with average steps
plot(averagesteps_perinterval, 
     type = 'l', 
     xlab = 'Interval', 
     ylab = 'Number of steps', 
     main = 'Average daily activity pattern')

#Find the interval with the max average number of steps
cat("The 5-minute interval, on average across all the days in the dataset, that contains the maximum number of steps is: ", max(averagesteps_perinterval))
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
